import SSC.NormalForms

/-!
# Soundness of the Partial Weak-Normal Grammar

This module proves that every term recognized by the current `WeakNormalLike` grammar
has no outgoing weak step. The converse is not yet claimed because the grammar does not
contain the paper's normal explicit-substitution forms.

## Proof roadmap

The declarations are intentionally ordered as a dependency ladder:

1. `var_normal` and `lam_normal`: establish semantic normality for the two base shapes.
2. `weakAnswer_normal`: transfer lambda normality through the `WeakAnswer` predicate.
3. `inert_not_plugS_lam`: exclude a multiplicative redex at the head of an inert term.
4. `inert_normal` / `weakNormalLike_normal`: mutually follow the grammar. An inert
   application delegates a step in its left or right child to the matching induction
   hypothesis, while the root case is excluded by step 3.

In short:

```text
variable/lambda shape
  -> weak-answer normality
  -> inert-head exclusion
  -> mutual inert/weak-normal-like soundness
```
-/

namespace SSC

open Term

/-- A variable cannot contain a root redex in any weak-context decomposition. -/
theorem var_normal (x : Nat) : NormalForm (Term.var x) := by
  intro h
  rcases h with ⟨u, C, r, s, hroot, hs, ht⟩
  -- Every non-empty weak context constructs a non-variable outer shape.
  cases C <;> simp [plugW] at hs
  · cases hs
    -- The remaining empty-context case would require a root step from a variable.
    cases hroot <;> rename_i impossible <;> cases impossible

/-- Weak evaluation never enters a lambda, and no root rule starts from one. -/
theorem lam_normal (x : Nat) (t : Term) : NormalForm (Term.lam x t) := by
  intro h
  rcases h with ⟨u, C, r, s, hroot, hs, ht⟩
  -- As for variables, only the empty context can have a lambda as its outer shape.
  cases C <;> simp [plugW] at hs
  · cases hs
    cases hroot <;> rename_i impossible <;> cases impossible

/-- The current weak answers are lambdas, so the base lambda theorem is sufficient. -/
theorem weakAnswer_normal {t : Term} (h : WeakAnswer t) : NormalForm t := by
  cases h with
  | lam =>
      exact lam_normal _ _

/--
An inert term cannot be a lambda wrapped only in explicit substitutions.

This shape exclusion is exactly what rules out a multiplicative root redex when proving
that an inert-headed application is normal.
-/
theorem inert_not_plugS_lam {i : Term} (hi : Inert i) (S : SCtx) (x : Nat) (t : Term) :
    i ≠ plugS S (Term.lam x t) := by
  intro heq
  induction S with
  | hole =>
      simp [plugS] at heq
      cases hi <;> contradiction
  | es S' y v ih =>
      -- A non-empty substitution context has `es` as its outer constructor, while the
      -- current inert grammar has only variables and applications.
      simp [plugS] at heq
      cases hi <;> contradiction

mutual

/-- Every term generated by the current inert grammar is weak-normal. -/
theorem inert_normal : {t : Term} → Inert t → NormalForm t
  | _, .var => var_normal _
  | _, @Inert.app i n hi hn => by
      -- Mutual induction is necessary because an inert application contains a
      -- `WeakNormalLike` argument, which may in turn contain an inert term.
      have inertHeadNormal := inert_normal hi
      have argumentNormal := weakNormalLike_normal hn
      intro hstep
      rcases hstep with ⟨u, C, r, s, hroot, hs, ht⟩
      cases C with
      | hole =>
          -- At the root, only the multiplicative rule could match an application.
          -- Its function would have to be a substitution-context-wrapped lambda,
          -- contradicting the inert-head exclusion lemma above.
          simp [plugW] at hs
          subst hs
          cases hroot with
          | m multiplicative =>
              cases multiplicative
              exact inert_not_plugS_lam hi _ _ _ rfl
          | e impossible =>
              cases impossible
          | gcv impossible =>
              cases impossible
      | appL C' u' =>
          -- A step selected in the function produces an outgoing step from `i`.
          simp [plugW] at hs
          rcases hs with ⟨h1, h2⟩
          have headStep : Step i (plugW C' s) := by
            refine ⟨C', r, s, hroot, h1, rfl⟩
          exact inertHeadNormal ⟨plugW C' s, headStep⟩
      | appR s' C' =>
          -- A step selected in the argument contradicts its mutual induction result.
          simp [plugW] at hs
          rcases hs with ⟨h1, h2⟩
          have argumentStep : Step n (plugW C' s) := by
            refine ⟨C', r, s, hroot, h2, rfl⟩
          exact argumentNormal ⟨plugW C' s, argumentStep⟩
      | esL C' x u' =>
          -- An `es` context cannot reconstruct an application at the outermost level.
          simp [plugW] at hs
      | esR s' x C' =>
          -- The same constructor mismatch closes a hole in an ES replacement.
          simp [plugW] at hs

/-- Every term generated by the current weak-normal-like grammar is weak-normal. -/
theorem weakNormalLike_normal : {t : Term} → WeakNormalLike t → NormalForm t
  | _, .answer ha => weakAnswer_normal ha
  | _, .inert hi => inert_normal hi

end

end SSC
